@startuml

start

:Create an header file;
:Declare 3 external functions for each task;
:Create different source file for each task;
:Include header file inside all source files;
:Create a main file with global variable, Menu and Switch Cases;
:Include header file in main file;
:Display Menu;
:Declare variable choice;
:Read Choice/

while (choice is not exit) is (Yes)

:Switch Choice;

fork

-> case1;
:fibonacci series;

fork again

-> case2;
:factorial;

fork again

-> case3;
:prime numbers;

fork again

-> case4;
:modify range;

end fork

:Display output;
:Read Choice/

end while (No)

stop

@enduml


/'repeat
if (input range = 0) then (yes)
:print 0;
else
endif
if (input range = 1) then (yes)
:print 1;
else (No)
:Next value = Previous value + Current value;
:Print next value;'/